// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PDE.DataAccess;

#nullable disable

namespace PDE.DataAccess.Migrations
{
    [DbContext(typeof(DBPDEContext))]
    [Migration("20220425164111_NuevoModelos4")]
    partial class NuevoModelos4
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("PDE.Models.Entities.Cargo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Cargo", (string)null);
                });

            modelBuilder.Entity("PDE.Models.Entities.CargoTerritorial", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("CargoId")
                        .HasColumnType("int");

                    b.Property<int>("LocalidadId")
                        .HasColumnType("int");

                    b.Property<int?>("SupervisorId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CargoId");

                    b.HasIndex("LocalidadId");

                    b.HasIndex("SupervisorId");

                    b.ToTable("CargoTerritorial", (string)null);
                });

            modelBuilder.Entity("PDE.Models.Entities.Categoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LlevaColegio")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LlevaDatosActa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LlevaDatosPasaporte")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PuedeVotar")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categorias");
                });

            modelBuilder.Entity("PDE.Models.Entities.Colegio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int?>("CantidadInscritos")
                        .HasColumnType("int");

                    b.Property<int?>("CantidadReservada")
                        .HasColumnType("int");

                    b.Property<string>("CodigoColegio")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<short>("Idmunicipio")
                        .HasColumnType("smallint");

                    b.Property<int>("Idrecinto")
                        .HasColumnType("int");

                    b.Property<Guid?>("RegId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TieneCupo")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Colegios");
                });

            modelBuilder.Entity("PDE.Models.Entities.EstadoCivil", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("RegId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("EstadoCiviles");
                });

            modelBuilder.Entity("PDE.Models.Entities.Localidad", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Localidad", (string)null);
                });

            modelBuilder.Entity("PDE.Models.Entities.Miembro", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Apellidos")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<int>("CargoTerritorialId")
                        .HasColumnType("int");

                    b.Property<int>("CategoriaId")
                        .HasColumnType("int");

                    b.Property<string>("Cedula")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.Property<string>("Celular")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nchar(10)")
                        .IsFixedLength();

                    b.Property<int?>("ColegioId")
                        .HasColumnType("int");

                    b.Property<int?>("EstadoCivilId")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaNacimiento")
                        .HasColumnType("datetime");

                    b.Property<string>("LugarNacimiento")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("MunicipioId")
                        .HasColumnType("int");

                    b.Property<int?>("NacionalidadId")
                        .HasColumnType("int");

                    b.Property<string>("Nombres")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<int?>("OcupacionId")
                        .HasColumnType("int");

                    b.Property<int?>("SexoId")
                        .HasColumnType("int");

                    b.Property<int?>("SupervisorId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CargoTerritorialId");

                    b.HasIndex("CategoriaId");

                    b.HasIndex("EstadoCivilId");

                    b.HasIndex("MunicipioId");

                    b.HasIndex("NacionalidadId");

                    b.HasIndex("OcupacionId");

                    b.HasIndex("SexoId");

                    b.HasIndex("SupervisorId");

                    b.ToTable("Miembro", (string)null);
                });

            modelBuilder.Entity("PDE.Models.Entities.Municipio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Dm")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Estatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<int?>("IdUsuarioCreacion")
                        .HasColumnType("int");

                    b.Property<int?>("IdUsuarioModificacion")
                        .HasColumnType("int");

                    b.Property<int?>("MunicipioPadreId")
                        .HasColumnType("int");

                    b.Property<double?>("Oficio")
                        .HasColumnType("float");

                    b.Property<int>("ProvinciaId")
                        .HasColumnType("int");

                    b.Property<Guid?>("RegId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("Municipios");
                });

            modelBuilder.Entity("PDE.Models.Entities.Nacionalidad", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Estatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gentilicio")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("RegId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Siglas")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Nacionalidads");
                });

            modelBuilder.Entity("PDE.Models.Entities.Ocupacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Estatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("RegId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("RequiereTitulo")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Ocupacions");
                });

            modelBuilder.Entity("PDE.Models.Entities.Sexo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<int?>("IdUsuarioCreacion")
                        .HasColumnType("int");

                    b.Property<int?>("IdUsuarioModificacion")
                        .HasColumnType("int");

                    b.Property<Guid?>("RegId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("Sexo");
                });

            modelBuilder.Entity("PDE.Models.Entities.CargoTerritorial", b =>
                {
                    b.HasOne("PDE.Models.Entities.Cargo", "Cargo")
                        .WithMany("CargoTerritorialCargos")
                        .HasForeignKey("CargoId")
                        .IsRequired()
                        .HasConstraintName("FK_CargoTerritorial_Cargo");

                    b.HasOne("PDE.Models.Entities.Localidad", "Localidad")
                        .WithMany("CargoTerritorials")
                        .HasForeignKey("LocalidadId")
                        .IsRequired()
                        .HasConstraintName("FK_CargoTerritorial_Localidad");

                    b.HasOne("PDE.Models.Entities.Cargo", "Supervisor")
                        .WithMany("CargoTerritorialSupervisors")
                        .HasForeignKey("SupervisorId")
                        .HasConstraintName("FK_CargoTerritorial_SupervisorId");

                    b.Navigation("Cargo");

                    b.Navigation("Localidad");

                    b.Navigation("Supervisor");
                });

            modelBuilder.Entity("PDE.Models.Entities.Miembro", b =>
                {
                    b.HasOne("PDE.Models.Entities.CargoTerritorial", "CargoTerritorial")
                        .WithMany()
                        .HasForeignKey("CargoTerritorialId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PDE.Models.Entities.Categoria", "Categoria")
                        .WithMany("Miembros")
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PDE.Models.Entities.EstadoCivil", "EstadoCivil")
                        .WithMany()
                        .HasForeignKey("EstadoCivilId");

                    b.HasOne("PDE.Models.Entities.Municipio", "Municipio")
                        .WithMany()
                        .HasForeignKey("MunicipioId");

                    b.HasOne("PDE.Models.Entities.Nacionalidad", "Nacionalidad")
                        .WithMany()
                        .HasForeignKey("NacionalidadId");

                    b.HasOne("PDE.Models.Entities.Ocupacion", "Ocupacion")
                        .WithMany()
                        .HasForeignKey("OcupacionId");

                    b.HasOne("PDE.Models.Entities.Sexo", "Sexo")
                        .WithMany()
                        .HasForeignKey("SexoId");

                    b.HasOne("PDE.Models.Entities.Miembro", "Supervisor")
                        .WithMany("InverseSupervisor")
                        .HasForeignKey("SupervisorId")
                        .HasConstraintName("FK_Miembro_Miembro");

                    b.Navigation("CargoTerritorial");

                    b.Navigation("Categoria");

                    b.Navigation("EstadoCivil");

                    b.Navigation("Municipio");

                    b.Navigation("Nacionalidad");

                    b.Navigation("Ocupacion");

                    b.Navigation("Sexo");

                    b.Navigation("Supervisor");
                });

            modelBuilder.Entity("PDE.Models.Entities.Cargo", b =>
                {
                    b.Navigation("CargoTerritorialCargos");

                    b.Navigation("CargoTerritorialSupervisors");
                });

            modelBuilder.Entity("PDE.Models.Entities.Categoria", b =>
                {
                    b.Navigation("Miembros");
                });

            modelBuilder.Entity("PDE.Models.Entities.Localidad", b =>
                {
                    b.Navigation("CargoTerritorials");
                });

            modelBuilder.Entity("PDE.Models.Entities.Miembro", b =>
                {
                    b.Navigation("InverseSupervisor");
                });
#pragma warning restore 612, 618
        }
    }
}
